// tslint:disable: no-var-requires
export const CurvyTopBg = require('./curvy_top_bg.png')
export const CurvyBottomBg = require('./curvy_bottom_bg.png')

export const TabbarDashboard = require('./tabbar_dashboard.png')
export const TabbarCalendar = require('./tabbar_calendar.png')
export const TabbarDiary = require('./tabbar_diary.png')
export const TabbarSettings = require('./tabbar_settings.png')
export const TabbarLover = require('./tabbar_friend.png')

export const ImageButtonAddEmotion = require('./btn_add_emotion.png')
export const ImageButtonNotification = require('./btn_notification.png')
export const ImageButtonSendNotification = require('./btn_send_noti.png')

export const IconEdit = require('./icon_edit.png')
export const IconChatNoti = require('./icon_chat_noti.png')
export const IconPeople = require('./icon_people.png')

export const Logo = require('./logo.png')
export const Jar = require('./jar.png')

export const InputPlaceHolderJar = require('./input_placeholder_jar.png')
export const InputPlaceHolderSecure = require('./input_placeholder_secure.png')
export const LoadingGif = require('./loading.gif')

export const LoverJar = require('./lover_jar.png')

export const EmojiTypeHeart = require(`../../../assets/emoji_heart.png`)
export const EmojiTypeAfraid = require(`../../../assets/emojis/afraid.png`)
export const EmojiTypeAmused = require(`../../../assets/emojis/amused.png`)
export const EmojiTypeAngry = require(`../../../assets/emojis/angry.png`)
export const EmojiTypeAnxious = require(`../../../assets/emojis/anxious.png`)
export const EmojiTypeAshamed = require(`../../../assets/emojis/ashamed.png`)
export const EmojiTypeBashful = require(`../../../assets/emojis/bashful.png`)
export const EmojiTypeBored = require(`../../../assets/emojis/bored.png`)
export const EmojiTypeCold = require(`../../../assets/emojis/cold.png`)
export const EmojiTypeConfident = require(`../../../assets/emojis/confident.png`)
export const EmojiTypeConfused = require(`../../../assets/emojis/confused.png`)
export const EmojiTypeCrazy = require(`../../../assets/emojis/crazy.png`)
export const EmojiTypeCurious = require(`../../../assets/emojis/curious.png`)
export const EmojiTypeDepressed = require(`../../../assets/emojis/depressed.png`)
export const EmojiTypeDetermined = require(`../../../assets/emojis/determined.png`)
export const EmojiTypeEnraged = require(`../../../assets/emojis/enraged.png`)
export const EmojiTypeEnvious = require(`../../../assets/emojis/envious.png`)
export const EmojiTypeFrightened = require(`../../../assets/emojis/frightened.png`)
export const EmojiTypeHappy = require(`../../../assets/emojis/happy.png`)
export const EmojiTypeHot = require(`../../../assets/emojis/hot.png`)
export const EmojiTypeIndifferent = require(`../../../assets/emojis/indifferent.png`)
export const EmojiTypeJealous = require(`../../../assets/emojis/jealous.png`)
export const EmojiTypeLove = require(`../../../assets/emojis/love.png`)
export const EmojiTypeMiserable = require(`../../../assets/emojis/miserable.png`)
export const EmojiTypeSad = require(`../../../assets/emojis/sad.png`)
export const EmojiTypeSick = require(`../../../assets/emojis/sick.png`)
export const EmojiTypeSorry = require(`../../../assets/emojis/sorry.png`)
export const EmojiTypeStupid = require(`../../../assets/emojis/stupid.png`)
export const EmojiTypeSurprised = require(`../../../assets/emojis/surprised.png`)
export const EmojiTypeSuspicious = require(`../../../assets/emojis/suspicious.png`)
export const EmojiTypeWithdraw = require(`../../../assets/emojis/withdraw.png`)
