// tslint:disable: no-var-requires
export const CurvyTopBg = require('./curvy_top_bg.png')
export const CurvyBottomBg = require('./curvy_bottom_bg.png')

export const TabbarDashboard = require('./tabbar_dashboard.png')
export const TabbarCalendar = require('./tabbar_calendar.png')
export const TabbarDiary = require('./tabbar_diary.png')
export const TabbarSettings = require('./tabbar_settings.png')
export const TabbarLover = require('./tabbar_friend.png')

export const ImageButtonAddEmotion = require('./btn_add_emotion.png')
export const ImageButtonNotification = require('./btn_notification.png')
export const ImageButtonSendNotification = require('./btn_send_noti.png')

export const IconEdit = require('./icon_edit.png')
export const IconChatNoti = require('./icon_chat_noti.png')
export const IconPeople = require('./icon_people.png')

export const Logo = require('./logo.png')
export const Jar = require('./jar.png')

export const InputPlaceHolderJar = require('./input_placeholder_jar.png')
export const InputPlaceHolderSecure = require('./input_placeholder_secure.png')
export const LoadingGif = require('./loading.gif')

export const LoverJar = require('./lover_jar.png')

export const EmojiTypeHeart = require(`./emoji_heart.png`)
export const EmojiTypeAfraid = require(`./emojis/afraid.png`)
export const EmojiTypeAmused = require(`./emojis/amused.png`)
export const EmojiTypeAngry = require(`./emojis/angry.png`)
export const EmojiTypeAnxious = require(`./emojis/anxious.png`)
export const EmojiTypeAshamed = require(`./emojis/ashamed.png`)
export const EmojiTypeBashful = require(`./emojis/bashful.png`)
export const EmojiTypeBored = require(`./emojis/bored.png`)
export const EmojiTypeCold = require(`./emojis/cold.png`)
export const EmojiTypeConfident = require(`./emojis/confident.png`)
export const EmojiTypeConfused = require(`./emojis/confused.png`)
export const EmojiTypeCrazy = require(`./emojis/crazy.png`)
export const EmojiTypeCurious = require(`./emojis/curious.png`)
export const EmojiTypeDepressed = require(`./emojis/depressed.png`)
export const EmojiTypeDetermined = require(`./emojis/determined.png`)
export const EmojiTypeEnraged = require(`./emojis/enraged.png`)
export const EmojiTypeEnvious = require(`./emojis/envious.png`)
export const EmojiTypeFrightened = require(`./emojis/frightened.png`)
export const EmojiTypeHappy = require(`./emojis/happy.png`)
export const EmojiTypeHot = require(`./emojis/hot.png`)
export const EmojiTypeIndifferent = require(`./emojis/indifferent.png`)
export const EmojiTypeJealous = require(`./emojis/jealous.png`)
export const EmojiTypeLove = require(`./emojis/love.png`)
export const EmojiTypeMiserable = require(`./emojis/miserable.png`)
export const EmojiTypeSad = require(`./emojis/sad.png`)
export const EmojiTypeSick = require(`./emojis/sick.png`)
export const EmojiTypeSorry = require(`./emojis/sorry.png`)
export const EmojiTypeStupid = require(`./emojis/stupid.png`)
export const EmojiTypeSurprised = require(`./emojis/surprised.png`)
export const EmojiTypeSuspicious = require(`./emojis/suspicious.png`)
export const EmojiTypeWithdraw = require(`./emojis/withdraw.png`)
